package com.mathours.dal;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBAutoGeneratedKey;

@DynamoDBTable(tableName="Ranks")
public class Rank {
	private int id;
	private String belt;
	private int stripe;
	private int requiredHours;
	
	@DynamoDBHashKey(attributeName="RankID")
	@DynamoDBAutoGeneratedKey
	public int getId()
	{
		return id;
	}
	public void setId(int value) 
	{
		id = value;
	}

	@DynamoDBAttribute(attributeName="Belt")
	public String getBelt()
	{
		return belt;
	}
	public void setBelt(String value) 
	{
		belt = value;
	}
	
	@DynamoDBAttribute(attributeName="Stripe")
	public int getStripe()
	{
		return stripe;
	}
	public void setStripe(int value) 
	{
		stripe = value;
	}
	
	@DynamoDBAttribute(attributeName="RequiredHours")
	public int getRequiredHours()
	{
		return requiredHours;
	}
	public void setRequiredHours(int value) 
	{
		requiredHours = value;
	}
}
